FROM frrouting/frr
LABEL node_type="router"
RUN sed -i -e 's/^bgpd=no/bgpd=yes/' \
           -e 's/^ospfd=no/ospfd=yes/' \
           -e 's/^isisd=no/isisd=yes/' /etc/frr/daemons
RUN echo "service integrated-vtysh-config" > /etc/frr/vtysh.conf && \
    echo "hostname frr" >> /etc/frr/vtysh.conf
