HOST_DIR := host/
ROUTER_DIR := router/

HOST1_CONFIG := $(HOST_DIR)/host1.sh
HOST2_CONFIG := $(HOST_DIR)/host2.sh
HOST3_CONFIG := $(HOST_DIR)/host2.sh

ROUTER_LEAF1_CONFIG := $(ROUTER_DIR)/leaf_router1.sh
ROUTER_LEAF2_CONFIG := $(ROUTER_DIR)/leaf_router2.sh
ROUTER_LEAF3_CONFIG := $(ROUTER_DIR)/leaf_router3.sh
ROUTER_SPINE_CONFIG := $(ROUTER_DIR)/spine_router.sh

all:
	bash config.sh